In [1]:
import tensorflow as tf
tf.enable_eager_execution()

C:\Develop\Python\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
print(tf.add(1,2))

tf.Tensor(3, shape=(), dtype=int32)


In [5]:
print(tf.add([1,2],[3,4]))

tf.Tensor([4 6], shape=(2,), dtype=int32)


In [7]:
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))
print(tf.encode_base64("china dream"))

tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'Y2hpbmEgZHJlYW0', shape=(), dtype=string)


In [11]:
# 矩阵乘法
x = tf.matmul([[1,2]],[[3,4],[5,6]])
print(x)

tf.Tensor([[13 16]], shape=(1, 2), dtype=int32)


In [12]:
# NumPy Compatibility

In [13]:
import numpy as np
x = np.ones((2,3))
print(tf.multiply(x,4))

tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]], shape=(2, 3), dtype=float64)


In [16]:
# GPU acceleration
print(tf.test.is_gpu_available())

False


In [18]:
x = tf.random_uniform([3,4])
print(x.device.endswith('GPU:0'))

False


In [19]:
# Explicit Device Placement
# 未看
def time_matmul(x):
  %timeit tf.matmul(x, x)

# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
  x = tf.random_uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)

# Force execution on GPU #0 if available
if tf.test.is_gpu_available():
  with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
    x = tf.random_uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:


41.8 ms ± 2.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
